[project]
name = "fraud-e2e"
version = "0.1.0"
description = "End-to-end fraud detection & analytics"
readme = "README.md"
requires-python = ">=3.11"
dependencies = []

[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = ["."]
filterwarnings = [
  "ignore::UserWarning",
]
addopts = "-q"

